name: STCOGAT
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - nvidia
  - defaults
  - anaconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch
  - bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.9.0
  - aom=3.6.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - cccl=2.8.2
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.2
  - cuda-cccl=12.9.27
  - cuda-cccl_linux-64=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.9.19
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - dav1d=1.2.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - ffmpeg=6.1.1
  - filelock=3.18.0
  - fontconfig=2.14.1
  - fqdn=1.5.1
  - freetype=2.10.4
  - fsspec=2025.5.1
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.36.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.6.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libglib=2.78.4
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.39
  - libpq=12.20
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtheora=1.1.1
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuuid=1.41.5
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpir=3.0.0
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - opentelemetry-api=1.33.1
  - overrides=7.7.0
  - packaging=25.0
  - pandoc=3.7.0.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - ply=3.11
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-annoy=1.17.3
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pywin32=307
  - pywinpty=2.0.10
  - pyyaml=6.0.2
  - pyzmq=24.0.1
  - qt-main=5.15.2
  - qtconsole=5.6.1
  - qtconsole-base=5.6.1
  - qtpy=2.4.3
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.25.1
  - send2trash=1.8.3
  - sip=6.7.12
  - six=1.17.0
  - sleef=3.8
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.45.3
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - terminado=0.18.1
  - tesseract=5.2.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250516
  - typing_utils=0.1.0
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiobotocore==2.24.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.4
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - alembic==1.16.3
      - anndata==0.11.4
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - biothings-client==0.4.1
      - botocore==1.39.11
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmcrameri==1.9
      - colorcet==3.1.0
      - colorlog==6.9.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.2
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - fasteners==0.20
      - fonttools==4.58.1
      - frozenlist==1.6.0
      - geopandas==1.1.1
      - greenlet==3.2.3
      - gseapy==1.1.8
      - gudhi==3.11.0
      - h5py==3.13.0
      - harmonypy==0.0.10
      - igraph==0.11.8
      - imageio==2.37.0
      - inflect==7.5.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - kneed==0.8.5
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - llvmlite==0.44.0
      - locket==1.0.0
      - louvain==0.8.2
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - matplotlib==3.10.3
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - multidict==6.4.4
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.3
      - mygene==3.2.2
      - natsort==8.4.0
      - networkx==2.8.8
      - numba==0.61.2
      - numcodecs==0.13.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - ome-zarr==0.11.1
      - omnipath==1.0.12
      - openpyxl==3.1.5
      - optuna==4.4.0
      - pandas==2.2.3
      - param==2.2.1
      - partd==1.4.2
      - patsy==1.0.1
      - pims==0.7
      - pooch==1.8.2
      - pot==0.9.5
      - propcache==0.3.1
      - pyarrow==21.0.0
      - pyct==0.5.0
      - pynndescent==0.5.13
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - rich==14.1.0
      - rpy2==3.6.0
      - rpy2-rinterface==3.6.0
      - rpy2-robjects==3.6.0
      - s3fs==2025.5.1
      - scanpy==1.11.2
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - session-info==1.0.1
      - session-info2==0.1.2
      - setuptools==70.2.0
      - shapely==2.1.1
      - slicerator==1.1.0
      - spatial-image==1.2.3
      - spatialdata==0.5.0
      - sqlalchemy==2.0.41
      - squidpy==1.6.5
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - toolz==1.0.0
      - torch==2.7.0+cu128
      - torch-cluster==1.6.3+pt27cu128
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cu128
      - torch-sparse==0.6.18+pt27cu128
      - torch-spline-conv==1.2.2+pt27cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.67.1
      - triton==3.3.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap-learn==0.5.7
      - validators==0.35.0
      - xarray==2025.6.1
      - xarray-dataclass==3.0.0
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.20.0
      - zarr==2.18.3
